### ISSUE TITLE
how bandwidth values are computed ?

### ISSUE THREAD

**Issue by mhow2** [matomo-org/plugin-Bandwidth#19]
On https://plugins.matomo.org/Bandwidth#faq it's explained which new fields/values we are expected to see either using API or UI. However, there is no documentation on _how_ it's computed.
For example I don't see from where comes **min_bandwidth** and **max_bandwidth**. Is it something coming from 206 status codes ?

**Comment by mhow2** [comment]
I think I understand : It should be because a given file with same filename could be updated and its size changed during the selected period. Anyway, glossary entries would be welcome.

**Comment by heurteph-ei** [comment]
Hi @AltamashShaikh
Maybe this only left ticket can be completed ?

**Comment by AltamashShaikh** [comment]
@heurteph-ei Will check this one and update here if I can find the relevant info

**Comment by AltamashShaikh** [comment]
@heurteph-ei @mhow2  I looked into the code
1. `sum` is sum of all requests where `bw_bytes` was supplied
2. `min` is min of `bw_bytes` where `bw_bytes` was supplied
3. `max` is max of `bw_bytes` where `bw_bytes` was supplied
4. `avg` is sum(bw_bytes)/no of requests where bw_bytes was passed

Eg: We track `pageviews` with following `bw_bytes` [1, 10, null, 5, null, 3949, 399]
So sum will be (1+10+5+3949+399) `4364`
min will be `1`
max will be `3949`
average will be (4364/5) `872`

Does mentioning the same in the [FAQ file](https://plugins.matomo.org/Bandwidth#faq) works ?

**Comment by heurteph-ei** [comment]
Hi @AltamashShaikh 
As we don't have any feedback from @mhow2, I think that just adding the information you provided in your last post would do the job :wink:
